services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    # Run a command against the development stage of the image
    command: yarn start:dev
    ports:
      - 3001:3001
    depends_on:
      - db
    networks:
      - backend
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432
    ports:
      - '5433:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend: